# hostnames (like "hostA2C") must be MAX 8 characters long, else playbooks will fail in many ways

all:
  children:
    cloudA:
      vars:
        eth0: lm_cloudA
        cloud: A
      hosts:
        hostA.cloudA.test:
        hostA2B.cloudA.test:
          eth2: lm_xlinkAB
        hostA2C.cloudA.test:
          eth2: lm_xlinkAC
    cloudB:
      vars:
        eth0: lm_cloudB
        cloud: B
      hosts:
        hostB2A.cloudB.test:
          eth2: lm_xlinkAB
        hostB2D.cloudB.test:
          eth2: lm_xlinkBD
        hostB.cloudB.test:
          eth2: lm_ilinkBF
        hostF.cloudB.test:
          eth2: lm_ilinkBF
    cloudC:
      vars:
        eth0: lm_cloudC
        cloud: C
      hosts:
        hostC2A.cloudC.test:
          eth2: lm_xlinkAC
        hostC.cloudC.test:
    cloudD:
      vars:
        eth0: lm_cloudD
        cloud: D
      hosts:
        hostD2B.cloudD.test:
          eth2: lm_xlinkBD
        hostD.cloudD.test:
          eth2: lm_ilinkDF
        hostF.cloudD.test:
          eth2: lm_ilinkDF
